name: nfc
description: nfc rw
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Presentation
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.1
  cached_network_image: ^3.2.2

  # Logic
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  url_launcher: ^6.1.8

  # DI
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # CodeGen
  build_runner: ^2.2.1
  injectable_generator: ^2.1.3

  # DesignGen
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.9

flutter:
  uses-material-design: true

  assets:
    - assets/
